DATA:
  dataset: 'Aircraft'
  # path to Dataset DIRECTORY
  rootdir: './datasets/'             
  # INPUT IMAGE DIMENSION
  image_size: [224, 224, 3]          
HARDWARE:
  # CPU : -1 and GPU: 0/1
  gpu_id: -1
  # fraction of GPU to use range [0, 1]
  gpu_utilisation: 1                  
MODEL:
  # Set Batch size
  batch_size: 8
  # set model architecture, model_name available --> 'basecnn'; 'i2hofi'
  model_name: 'i2hofi'
  # PATH to trained models (to load from a particular checkpoint)
  checkpoint_path: 'TrainedModels/'   
  # Print model summary
  summary: True
  # To Save model at every checkpoint frequency
  save_model: False
  # To Save model with best validation accuracy (overwriting previous best)
  save_best_only: False
  # Load Model from checkpoint (to restart training)
  load_model: False
  # Backbone model
  backbone: 'Xception'
  # Freeze bacbone model (with pre-trained weights, such as ImageNet Weights)
  freeze_backbone: False
  # Enable/Disable GNN layer 1 (as a part of the model)
  gnn1_layr: True
  # Enable/Disable GNN layer 2 (as a part of the model)
  gnn2_layr: True
HYPERPARAMETERS:
  # Teleport probability in APPNP (gamma in the paper)
  alpha: 0.3
  # Upscale Resolution of backbone output feature map resolution
  ROIS_resolution: 42
  # Mimimum spatial allowed dimension of each roi when pooling
  minSize: 2
  # Grids to break Upsampled Feature horizontally and vertically
  ROIS_grid_size: 3
  # ROI resolution after pooling and resizing (default: 3 x 3)
  pool_size: 3
  # APPNP node feature dimension
  gcn_outfeat_dim : 512
  # GAT output node feature dimension
  gat_outfeat_dim : 512
  # dropout rate use everywhere
  dropout_rate : 0.2
  # L2 regularization in GATconv layer
  l2_reg : 2.5e-4
  # No. of heads to use in GAT attention
  attn_heads : 1
  # MLP activation in APPNP
  appnp_activation : 'sigmoid'
  # Activation to apply to GAT output
  gat_activation : 'elu'
  # Whether to concatenate or sum output if head > 1 used in GAT
  concat_heads : True
TRAIN:
  # To Restart training from a checkpoint epoch
  completed_epochs: 0
  # Frequency compute validation accuracy
  validation_freq: 2
  # Frequency save checkpoint
  checkpoint_freq: 2
  # Total training epochs
  epochs: 150
  # Initial Learning Rate (LR)
  lr: 0.01
  # Apply Step LR
  reduce_lr_bool: True
WANDB:
  # Project Name to Register to WandB
  wb_proj_name : 'I2HOFI_Aircraft'
  # Set Run name to appear in WandB
  run_name : 'None'
  # Condition whether to log in WandB
  wandb_log : False
  # WandB API key
  API_key: "########## REPLACE THIS STRING WITH YOUR WandB API HASH KEY ########"
COMPLEXITY:
  # Compute computatioal complexity of model
  calflops: False
